word_list = [
'abruptly', 
'absurd', 
'abyss', 
'affix', 
'askew', 
'avenue', 
'awkward', 
'axiom', 
'azure', 
'bagpipes', 
'bandwagon', 
'banjo', 
'bayou', 
'beekeeper', 
'bikini', 
'blitz', 
'blizzard', 
'boggle', 
'bookworm', 
'boxcar', 
'boxful', 
'buckaroo', 
'buffalo', 
'buffoon', 
'buxom', 
'buzzard', 
'buzzing', 
'buzzwords', 
'caliph', 
'cobweb', 
'cockiness', 
'croquet', 
'crypt', 
'curacao', 
'cycle', 
'daiquiri', 
'dirndl', 
'disavow', 
'dizzying', 
'duplex', 
'dwarves', 
'embezzle', 
'equip', 
'espionage', 
'euouae', 
'exodus', 
'faking', 
'fishhook', 
'fixable', 
'fjord', 
'flapjack', 
'flopping', 
'fluffiness', 
'flyby', 
'foxglove', 
'frazzled', 
'frizzled', 
'fuchsia', 
'funny', 
'gabby', 
'galaxy', 
'galvanize', 
'gazebo', 
'giaour', 
'gizmo', 
'glowworm', 
'glyph', 
'gnarly', 
'gnostic', 
'gossip', 
'grogginess', 
'haiku', 
'haphazard', 
'hyphen', 
'iatrogenic', 
'icebox', 
'injury', 
'ivory', 
'ivy', 
'jackpot', 
'jaundice', 
'jawbreaker', 
'jaywalk', 
'jazziest', 
'jazzy', 
'jelly', 
'jigsaw', 
'jinx', 
'jiujitsu', 
'jockey', 
'jogging', 
'joking', 
'jovial', 
'joyful', 
'juicy', 
'jukebox', 
'jumbo', 
'kayak', 
'kazoo', 
'keyhole', 
'khaki', 
'kilobyte', 
'kiosk', 
'kitsch', 
'kiwifruit', 
'klutz', 
'knapsack', 
'larynx', 
'lengths', 
'lucky', 
'luxury', 
'lymph', 
'marquis', 
'matrix', 
'megahertz', 
'microwave', 
'mnemonic', 
'mystify', 
'naphtha', 
'nightclub', 
'nowadays', 
'numbskull', 
'nymph', 
'onyx', 
'ovary', 
'oxidize', 
'oxygen', 
'pajama', 
'peekaboo', 
'phlegm', 
'pixel', 
'pizazz', 
'pneumonia', 
'polka', 
'pshaw', 
'psyche', 
'puppy', 
'puzzling', 
'quartz', 
'queue', 
'quips', 
'quixotic', 
'quiz', 
'quizzes', 
'quorum', 
'razzmatazz', 
'rhubarb', 
'rhythm', 
'rickshaw', 
'schnapps', 
'scratch', 
'shiv', 
'snazzy', 
'sphinx', 
'spritz', 
'squawk', 
'staff', 
'strength', 
'strengths', 
'stretch', 
'stronghold', 
'stymied', 
'subway', 
'swivel', 
'syndrome', 
'thriftless', 
'thumbscrew', 
'topaz', 
'transcript', 
'transgress', 
'transplant', 
'triphthong', 
'twelfth', 
'twelfths', 
'unknown', 
'unworthy', 
'unzip', 
'uptown', 
'vaporize', 
'vixen', 
'vodka', 
'voodoo', 
'vortex', 
'voyeurism', 
'walkway', 
'waltz', 
'wave', 
'wavy', 
'waxy', 
'wellspring', 
'wheezy', 
'whiskey', 
'whizzing', 
'whomever', 
'wimpy', 
'witchcraft', 
'wizard', 
'woozy', 
'wristwatch', 
'wyvern', 
'xylophone', 
'yachtsman', 
'yippee', 
'yoked', 
'youthful', 
'yummy', 
'zephyr', 
'zigzag', 
'zigzagging', 
'zilch', 
'zipper', 
'zodiac', 
'zombie', 
]

ya_novel_list = [' The Assasins Blade',' Throne of Glass ',' Crown of Midnight ',' Heir of Fire ',' Queen of Shadows ',' Empire of Storms ',' Tower of Dawn ',' Kingdom of Ash ',' A Court of Thorns and Roses ',' A Court of Mist and Fury ',' A Court of Wings and Ruin ',' A Court of Frost and Starlight ',' House of Earth and Blood Crescent City ',' The Cruel Prince ',' The Wicked King ',' The Queen of Nothing ',' Caraval ',' Legendary ',' Finale ',' Red Queen ',' Glass Sword ',' Kings Cage ',' War Storm ',' Cruel Crown ',' Six of Crows ',' Crooked Kingdom ',' Ash Princess ',' Lady Smoke ',' Ember Queen ',' King of Scars ',' City of Bones ',' City of Ashes ',' City of Glass ',' City of Fallen Angels ',' City of Lost Souls ',' City of Heavenly Fire ',' Shadow and Bone ',' Siege and Storm ',' Ruin and Rising ',' Three Dark Crowns ',' One Dark Throne ',' Two Dark Reigns ',' Five Dark Fates ',' Gemina ',' Illuminae ',' Memento ',' Obsidio ',' Everless ',' Evermore ',' The Cursed Sea ',' The Glass Spare ',' Courting Darkness ',' Igniting Darkness ',' Grave Mercy ',' Mortal Heart ',' The Shadows Between Us ',' Scythe ',' Thunderhead ',' The Toll ',' The Last Namsara ',' The Caged Queen ',' The Sky Weaver ',' Cinder ',' Cress ',' Scarlet ',' Fairest ',' Winter ',' Stars Above ',' Selection Band ',' The Elite ',' Crown ',' Heir ',' Graceling ',' Fire ',' Bitterblue ',' The Hunger Games ',' Catching Fire ',' The Ballad of Songbirds and Snakes ',' Shatter Me ',' Unravel Me ',' Ignite Me ',' Imagine Me ',' Destroy Me ',' Restore Me ',' Fracture Me ',' Defy Me ',' Furyborn ',' Kingsbane ',' Lightbringer ',' Sabriel ',' Lirael ',' Abhorsen ',' Clariel ',' Goldenhand ',' Aurora Rising ',' Aurora Burning ',' House of Dragons ',' Lady Midnight ',' Lord of Shadows ',' Queen of Air and Darkness ',' Clockwork Angel ',' Clockwork Prince ',' Clockwork Princess ',' Hobbit ',' The Lord of the Rings',' A Curse So Dark and Lonely ',' A Heart So Fierce and Broken ',' A Vow So Bold and Deadly ',' Game of Thrones ',' A Clash of Kings ',' A Storm of Swords ',' A Feast of Crows',' A Dance With Dragons ',' The Witcher',' Sword of Destiny ',' Season of Storms ',' Sorcery of Thorns ',' Serpent Dove ',' Blood Honey ',' Bone Crier s Moon ',' Burning Glass ',' Crystal Blade ',' Frozen Reign ',' The Gilded Wolves ',' Girls of Paper and Fire ',' Girls of Storm and Shadow ',' Fallen Lauren Kate ',' The Girl of Fire and Thorns ',' The False Prince ',' The Runaway King ',' The Shadow Throne ',' The Winners Curse ',' The Winners Crime ',' The Winners Kiss ',' Beautiful Creatures ',' Beautiful Darkness',' Beautiful Chaos',' Children of Blood and Bone ',' The Outcast ',' The Novice ',' The Inquisition ',' The Battlemage ',' Twilight Saga ',' Eragon ',' Eldest ',' Brisingr ',' Inheritance ',' ']

classic_novel_list = ['Pride and Prejudice',
'The Lord of the Rings',
'Jane Eyre',
'Harry Potter',
'To Kill a Mockingbird',
'Wuthering Heights',
'1984',
'His Dark Materials',
'Great Expectations',
'Little Women',
'Catch-22',
'Complete Works of Shakespeare',
'Rebecca',
'The Hobbit',   
'Birdsong',
'The Catcher in the Rye',
'The Time Travelers Wife',
'Middlemarch',
'Gone With the Wind',
'The Great Gatsby',  
'Bleak House',
'War and Peace',
'The Hitchhikers Guide to the Galaxy', 
'Brideshead Revisited',
'Crime and Punishment',
'The Grapes of Wrath', 
'Alice in Wonderland',
'The Wind in the Willows',  
'Anna Karenina',
'David Copperfield',
'The Chronicles of Narnia',
'Emma',
'Persuasion',
'The Alchemist',
'Kite Runner',   
'Captain CorelliS Mandolin',  
'Memoirs of a Geisha',  
'Winnie  The  Pooh',   
'Animal Farm',
'The Da Vinci Code',
'One Hundred Years of Solitude',
'A Prayer for Owen Meany',
'The Woman in White',  
'Anne of Green Gables',
'Far From the Madding Crowd',
'The Handmaids Tale'
'Lord of the Flies',
'Atonement',
'Life of Pi',
'Dune',
'Cold Comfort Farm',  
'Sense and Sensibility',
'A Suitable Boy',
'The Shadow of the Wind', 
'A Tale of Two Cities',
'Brave New World',
'The Curious Incident of the Dog in the Night Time',
'Love in the Time of Cholera',
'Of Mice and Men',
'Lolita',
'The Secret History',
'The Lovely Bones',
'The Count of Monte Cristo',
'On the Road',
'Jude the Obscure', 
'Bridget Jones Diary',  
'Midnights Children',
'Moby Dick',
'Oliver Twist',
'Dracula',
'The Secret Garden',
'Notes From a Small Island', 
'Ulysses',
'The Bell Jar',  
'Swallows and Amazons', 
'Germinal',
'Vanity Fair',
'Possession',
'A Christmas Carol',
'Cloud Atlas',
'The Color Purple',
'The Remains of the Day', 
'Madame Bovary',
'A Fine Balance', 
'Charlottes Web',
'The Five People You Meet in Heaven', 
'Adventures of Sherlock Holmes',
'The Faraway Tree Collection',
'Heart of Darkness',
'The Little Prince',
'The Wasp Factory',
'Watership Down',
'A Confederacy of Dunces',
'A Town Like Alice',
'The Three Musketeers',  
'A Clockwork Orange',
'Charlie and the Chocolate Factory',  
'Les Miserables']
